name: github page deploy

concurrency: 
  group: production
  cancel-in-progress: true

on: 
  push: 
    branches: -main
  pull_request: 
    branches: -main

jobs: 
  github-page-deploy: 
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy
      run: npm run deploy